# -*- coding: utf-8 -*-
"""sequentials.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1goFcOzz_a3EK_Is-y4uuzYN6HfmmCDoH
"""

print("Esse algoritmo faz uma busca sequencial em um array\nvarrendo todos os elementos, um por um, até encontrar o alvo")

def sequential_search(arr, target):
    """
    Faz uma busca sequencial no array para encontrar o elemento alvo
    """

    # O loop for percorre todo o array e compara todos os elementos com o alvo
    for i in range(len(arr)):
        if arr[i] == target:
            return i  # Retorna o indice se encontrado

# Examplo de uso:
arr = [3, 5, 1, 9, 2, 7, 6]
alvo = 15
resultado = sequential_search(arr, alvo)

# Se resultado == True
if resultado:
    print(f"Elemento {alvo} encontrado no indice {resultado}.")
# Se resultado == False
else:
    print(f"Elemento {alvo} nao foi encontrado na lista.")